### ISSUE TITLE
Setup.py inconsistency

### ISSUE THREAD

**Issue by MartyMacGyver** [storborg/python-packaging#18]
Setup.py refers to "README.rst.example" but everything.rst refers simply to README.rst - if you go strictly by http://python-packaging.readthedocs.org/en/latest/everything.html it won't work because it expects the README.rst.example, which isn't called out as a needed file on the page.

I'd suggest just renaming README.rst.example to README.rst and updating the reference in setup.py accordingly.

(I assume it was renamed to keep it from rendering the readme on the github page for https://github.com/storborg/python-packaging/tree/master/funniest - an empty README.md if present should take priority in rendering for the purpose of how github's UI displays things - see https://github.com/github/markup/issues/360 )

**Comment by MartyMacGyver** [comment]
For that matter, test_command_line.py refers to funniest.cmd - I assume that's a typo too?

**Comment by storborg** [comment]
Nice catch, cleaned up in c1798df751080d511dbb207edb5e632a64e7ef4c

**Comment by MartyMacGyver** [comment]
Thank you!
